### ISSUE TITLE
PDF417 Support

### ISSUE THREAD

**Issue by adearmasIAP** [Spelt/ZXing.Delphi#115]
Hello,
I have finished PDF417 translation from C# to Delphi.
It compiles just fine althought there's a lot of work to do left: 

- First of all Camera demo it does not work beause it cancels with AVs when it detects a PDF417 code. I cleaned up some errors but, obviusly some remain.
- There will be thousands of memory leaks because I tried to keep it as similar to the original as possible (Hoping to make it work fast but I failed). 
- I used a lot of compiler new goodies and I have to remove them to make ir compatible with older Delphi compilers.

I'd like to know if anyone with more experience than me would like to help to make ir work.

Regards.

**Comment by Spelt** [comment]
Did you continue developing your translation?

**Comment by adearmasIAP** [comment]
Hi!...
The translation is complete. I've been chasing an AV raised when a QR is detected but I couldn't fix it.
The code compiles. I had to change some classes that were not well translated (AFAIK)

Do you have time to help me? It is still written in 10.4.2 ( I guess it compiles well in 10.4.x) because I wanted to keep it as original as the C# code looks like in order to make it work.

Regards
________________________________
De: E Spelt ***@***.***>
Enviado: domingo, 25 de abril de 2021 10:18
Para: Spelt/ZXing.Delphi ***@***.***>
Cc: DE ARMAS ADRIAN ALFREDO ***@***.***>; Author ***@***.***>
Asunto: Re: [Spelt/ZXing.Delphi] PDF417 Support (#115)


Did you continue developing your translation?

**Comment by Spelt** [comment]
Short term, I have zero time to spare.  Long term I wil help but that won’t help you now.

**Comment by adearmasIAP** [comment]
It is OK. I made the translation when I had the time. It is not a functionality that I need for my own, I just wanted to collaborate with something that needed a good count of hours.
Every now and then, when I have the time, I keep chasing that AV.

Regards

**Comment by Tajmi** [comment]
@adearmasIAP Do you have any prototype source files with your PDF417 implementations?

**Comment by adearmasIAP** [comment]
Hello @Tajmi . I have the source code that I translated but it doesn't work at all.
The project I was working bought some PDF417 reading devices so I had no need to keep investigating the implementation.

If anyone wants to take a look I will happily upload it.

**Comment by Tajmi** [comment]
Hi @adearmasIAP  I would realy like to look at it and try to fix it. Can you contact me on VTajmr@seznam.cz or upload the source files anywhere? Thank you.

**Comment by adearmasIAP** [comment]
Hello @Tajmi I have uploaded my code. I needed an implementation of bigintegers so I used http://rvelthuis.de/programs/bigintegers.html

The code does not work, it raises an AV. 
There's a lot of work to do:
1.Make it work
2.To keep backward compability lots of inline variables should be removed
3.Memory leaks... I tried to translate the code without changes (that's the reason of inline variables) and that produced lots of ML. My idea was remove them before uploading the result.

https://drive.google.com/file/d/1a1GCIu4Btke0wBXTDSPtjOOs9dW1hkRr/view?usp=sharing

Hope you can make it work

**Comment by wilchaia** [comment]
Did anyone could make PDF417 decode work?

**Comment by Tajmr** [comment]
Yes I kinda make it. But it was hell work.

**Comment by Tajmr** [comment]
I got it running on delphi XE4, but it is still quit buggy :/

**Comment by adearmasIAP** [comment]
Is it possible to get the code and see if I can help?
________________________________
De: Tajmr ***@***.***>
Enviado: miércoles, 8 de junio de 2022 11:34
Para: Spelt/ZXing.Delphi ***@***.***>
Cc: DE ARMAS ADRIAN ALFREDO ***@***.***>; Mention ***@***.***>
Asunto: Re: [Spelt/ZXing.Delphi] PDF417 Support (#115)


I got it running on delphi XE4, but it is still quit buggy :/

**Comment by Tajmi** [comment]
I can post the code at the evening somewhere. I am no longer maintaining it. But if it can help anyone else.

**Comment by adearmasIAP** [comment]
Yes please
________________________________
De: Tajmi ***@***.***>
Enviado: martes, 11 de octubre de 2022 7:10
Para: Spelt/ZXing.Delphi ***@***.***>
Cc: DE ARMAS ADRIAN ALFREDO ***@***.***>; Mention ***@***.***>
Asunto: Re: [Spelt/ZXing.Delphi] PDF417 Support (#115)


I can post the code at the evening somewhere. I am no longer maintaining it. But if it cant help anyone else.

**Comment by balger** [comment]
Unfortunately I cannot help due to lack of knowledge. But I need PDF417. Thanks. Thanks. Thank you very much

**Comment by Spelt** [comment]
Hi Tajmi

Can you post the code?

**Comment by xelnaga64** [comment]
PDF417 still doesn't work

**Comment by balger** [comment]
Please PDF417

**Comment by xelnaga64** [comment]
Aztec format is not working either

**Comment by Spelt** [comment]
See: https://github.com/Spelt/ZXing.Delphi#other-barcodes

Is it for IOS, Android or Windows?

**Comment by xelnaga64** [comment]
> See: https://github.com/Spelt/ZXing.Delphi#other-barcodes
> 
> Is it for IOS, Android or Windows?

Hi. I need PDF417 and Aztec for Windows.
By the way, this gives 404 error: https://github.com/Redth/ZXing.Net.Mobile/blob/master/src/ZXing.Net/oned/Code39Reader.cs

**Comment by Spelt** [comment]
Its here in the dev branch from Redth: https://github.com/Redth/ZXing.Net/tree/f343fcd14fe1ff83700483d07ad65fd7d9ab9f73

He forked it from micjahn :  https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/oned/Code39Reader.cs

micjahn Seems more active
